name: CI

on: [push, pull_request]

jobs:

  test_os:
    name: OS ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11
          cache: 'maven'
      - name: Test
        run: ./mvnw -V --no-transfer-progress -e verify javadoc:javadoc

  sonar:
    name: Sonar code analysis
    runs-on: ubuntu-latest
    if: github.repository == 'assertj/assertj-guava' && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11
          cache: 'maven'
      - name: Build with Maven
        run: >
          ./mvnw -V --no-transfer-progress -e verify javadoc:javadoc
          org.sonarsource.scanner.maven:sonar-maven-plugin:3.7.0.1746:sonar
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.organization=assertj
          -Dsonar.projectKey=joel-costigliola_assertj-guava
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
